---

- name: Install the datanode packages
  sudo: yes
  yum: name={{item}} state=installed
  with_items: 
   - lzo
   - hadoop-hdfs-datanode
   - hadoop-lzo-cdh4
   - bigtop-utils

- include: ../../jar/tasks/datanode.yml
